# Dependabot version updates. Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Go Modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-updates:
        update-types:
          - "patch"
          - "minor"

  # Github Actions
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    groups:
      minor-updates:
        update-types:
          - "patch"
          - "minor"
