name: 🔬 PR Analysis

on:
  pull_request:

env:
  VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
  VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}

jobs:
  pr-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ingka-group-digital/ocp-pipelines/composites/go-pr@v2.28.1
        with:
          vault_role_id: ${{ env.VAULT_ROLE_ID }}
          vault_secret_id: ${{ env.VAULT_SECRET_ID }}
          go_version: "1.21"
