name: 🔖Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.go'

permissions:
  pull-requests: read
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Get latest tag
        uses: WyriHaximus/github-action-get-previous-tag@61819f33034117e6c686e6a31dba995a85afc9de # v2.0.0
        id: previous_version
        with:
          prefix: v

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # v1.75.0
        id: bump_version
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
          RELEASE_BRANCHES: main
          # custom tagging policy adapted to conventional commits
          MAJOR_STRING_TOKEN: feat!
          MINOR_STRING_TOKEN: feat
          DEFAULT_BUMP: patch

      - name: JFrog scanning
        uses: ingka-group/fastecho/.github/composites/jfrog@main
        with:
          jf_url: ${{ secrets.JF_URL }}
          jf_oidc_provider: ${{ secrets.JF_OIDC_PROVIDER }}
          jf_oidc_audience: ${{ secrets.JF_OIDC_AUDIENCE }}
          jf_repo: ${{ secrets.JF_GO_RELEASE_REPO }}
          version: ${{ steps.bump_version.outputs.new_tag }}

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@bcae7115752d4ed746ff92feb666574428a79415 # v6.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          fromTag: ${{ steps.previous_version.outputs.tag }}
          toTag: ${{ steps.bump_version.outputs.new_tag }}
          configurationJson: |
            {
              "sort": "DESC",
              "template": "## What’s Changed\n\n#{{UNCATEGORIZED}}",
              "pr_template": "* #{{TITLE}} (##{{NUMBER}})",
              "empty_template": "no changes"
            }

      - name: Verify changelog
        shell: bash
        run: |
          if [[ '${{ steps.build_changelog.outputs.failed }}' == 'true' ]]; then
            echo 'Error during building the changelog'
            exit 1
          fi

      - name: Create release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          prerelease: false
          draft: false
          name: "Release ${{ steps.bump_version.outputs.new_tag }}"
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          token: ${{ github.token }}
